
stages:
  - install
  - lint
  - test
  - build


install-python-job:
    stage: install
    script:
        - python --version
        - pip install poetry
        - pip install keyring -U
        - export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
        - cd solving-pacman-backend
        - python3 -m poetry install

test-python-job:
    stage: test
    script:
        - python3 -m poetry run pytest .

# install-react-job:
#   stage: install
#   script:
#     - echo "Installing npm packages..."
#     - cd solving-pacman-frontend
#     - npm install
#   cache:
#     key:
#       files:
#         - package-lock.json
#     paths:
#       - node_modules/
#     policy: pull-push
#   artifacts:
#     name: "artifacts"
#     untracked: true
#     expire_in: 60 mins
#     paths:
#       - .npm/
#       - node_modules/





# lint-react-job:
#   image: node:latest
#   stage: lint
#   script:
#     - echo "Linting react code..."
#     - npm run lint
#   allow_failure: false
#   interruptible: true
#   cache:
#     key:
#       files:
#         - package-lock.json
#     paths:
#       - node_modules/
#     policy: pull
#   artifacts:
#     reports:
#       codequality: gl-codequality.json

# test-react-job:
#   image: node:latest
#   stage: test
#   script:
#     - echo "Testing react code..."
#     - npm run test:ci
#   interruptible: true
#   coverage: '/^All files\s*\|\s*(\d+\.*\d+)/'
#   cache:
#     key:
#       files:
#         - package-lock.json
#     paths:
#       - node_modules/
#     policy: pull
#   artifacts:
#     paths:
#       - coverage
#     reports:
#         coverage_report:
#           coverage_format: cobertura
#           path: coverage/cobertura-coverage.xml
