stages:
  - install
  - lint
  - test
  - build

cache:
  key: modules
  paths:
    - solving-pacman-frontend/node_modules



##########################################
## PYTHON BACKEND JOBS
##########################################

install-python-job:
    stage: install
    script:
        - echo "Building Backend..."
        - (cd solving-pacman-backend && pip install -r requirements.txt)

test-python-job:
    stage: test
    script:
        - python3 -m coverage run -m pytest solving-pacman-backend
        - python3 -m coverage xml
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    artifacts:
      reports:
        coverage_report:
          coverage_format: cobertura
          path: coverage.xml

lint-python-job:
    stage: lint
    script:
        - cd solving-pacman-backend
        - python3 -m black .
        - python3 -m flake8 .


##########################################
## REACT FRONTEND JOBS
##########################################

install-react-job:
  stage: install
  script:
    - echo "Building Frontend..."
    - (cd solving-pacman-frontend && npm ci --legacy-peer-deps)

lint-react-job:
  image: node:latest
  stage: lint
  script:
    - echo "Linting react code..."
    - (cd solving-pacman-frontend && npm run lint)
  allow_failure: false
  interruptible: true
  artifacts:
    reports:
      codequality: gl-codequality.json

test-react-job:
  image: node:latest
  stage: test
  script:
    - echo "Testing react code..."
    - (cd solving-pacman-frontend && npm run test:ci)
  interruptible: true
  coverage: '/^All files\s*\|\s*(\d+\.*\d+)/'
  artifacts:
    paths:
      - coverage
    reports:
        coverage_report:
          coverage_format: cobertura
          path: coverage/cobertura-coverage.xml
