version: "3.8"

services:
  backend:
    build:
      context: ./solving-pacman-backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    image: solving-pacman-backend

  frontend:
    build:
      context: ./solving-pacman-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    image: solving-pacman-frontend
