name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  # Trigger the build step only when a new tag is created
  release:
    types: [created]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt
        working-directory: solving-pacman-backend

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Front-End Dependencies
        run: |
          cd solving-pacman-frontend
          npm install

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint Back-End
        run: |
            black --check --line-length 88 .
            flake8 --max-line-length=88 .
        working-directory: solving-pacman-backend

      - name: Lint Front-End
        run: |
          cd solving-pacman-frontend
          npm run lint

  test:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test Back-End
        run: |
          cd solving-pacman-backend
          pytest

      - name: Python Interrogate Check
        uses: JackMcKew/python-interrogate-check@main
        with:
          path: 'solving-pacman-backend'

      - name: Test Front-End
        run: |
          cd solving-pacman-frontend
          npm run test:once

  build:
    name: Build Production Version
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Back-End
        run: |
          cd solving-pacman-backend
          # Add your commands to build the production version of the backend here

      - name: Build Front-End
        run: |
          cd solving-pacman-frontend
          # Add your commands to build the production version of the frontend here
